"""init migrations

Revision ID: b194455a24de
Revises: 
Create Date: 2023-11-20 00:32:23.872081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b194455a24de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missing_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('previous_translates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('ind', sa.Integer(), nullable=True),
    sa.Column('tyv', sa.String(), nullable=True),
    sa.Column('ru', sa.String(), nullable=True),
    sa.Column('split', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tyvan_word', sa.String(), nullable=False),
    sa.Column('russian_word', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('telegram_full_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translates')
    op.drop_table('previous_translates')
    op.drop_table('missing_words')
    # ### end Alembic commands ###
